name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
<<<<<<< HEAD
      - run: npm ci && npm run
=======
      - run: npm install && npm run
>>>>>>> parent of a970d81 (tes)
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_GREENZEN_5E4AB }}
          channelId: live
          projectId: greenzen-5e4ab